language: c
sudo: false
compiler:
- clang
- gcc
cache:
  - ccache
  - pip
os:
  - linux
  - osx

env:
  global:
    - USE_CCACHE=1
    - CCACHE_SLOPPINESS=pch_defines,time_macros
    - CCACHE_COMPRESS=1
    - CCACHE_MAXSIZE=100M
    - PATH="$HOME/.local/bin:$HOME/Library/Python/2.7/bin:$PATH"

before_script:
  - mkdir $HOME/.local/
  - curl -O https://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.sh
  - sh cmake-3.4.3-Linux-x86_64.sh --prefix="$HOME/.local/" --skip-license
  - set -o pipefail
  - pip install --user cmakelint colout
  - ./configure

script:
  - make all -j 2 2>&1 | colout -t g++

addons:
  apt:
    packages:
      - valgrind
