language: c
sudo: false
compiler:
- clang
- gcc
cache:
  - ccache
  - pip
os:
  - linux
  - osx

env:
  global:
    - USE_CCACHE=1
    - CCACHE_SLOPPINESS=pch_defines,time_macros
    - CCACHE_COMPRESS=1
    - CCACHE_MAXSIZE=100M
    - PATH="$HOME/.local/bin:$PATH"

before_script:
  - set -o pipefail
  - pip install --user --upgrade pip setuptools wheel
  - pip install --user cmakelint colout
  - cmake --version
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON . 2>&1 | colout -t cmake

script:
  - make all -j 2 2>&1 | colout -t g++

addons:
  apt:
    packages:
      - cmake
      - valgrind
