language: c
sudo: false
compiler:
- clang
- gcc
cache:
  - ccache
  - pip

env:
  global:
    - USE_CCACHE=1
    - CCACHE_SLOPPINESS=pch_defines,time_macros
    - CCACHE_COMPRESS=1
    - CCACHE_MAXSIZE=100M

before_script:
  - pip install cmakelint colout
  - cmake . | colout -t cmake

script:
  - make -j 2 | colout -t g++
  - make test | colout -t g++

addons:
  apt:
    packages:
      - cmake
      - valgrind
