language: c
# TODO: Use sudo: false when PPA for CMake 3 is found
sudo: required
dist: trusty
compiler:
- clang
- gcc
cache:
  - ccache
  - pip
os:
  - linux
  - osx

env:
  global:
    - USE_CCACHE=1
    - CCACHE_SLOPPINESS=pch_defines,time_macros
    - CCACHE_COMPRESS=1
    - CCACHE_MAXSIZE=100M
    - PATH="$HOME/.local/bin:$HOME/Library/Python/2.7/bin:$PATH"

before_script:
  - set -o pipefail
  - pip install --user cmakelint colout
  - cmake --version
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -Wno-dev . 2>&1 | colout -t cmake

script:
  - make all -j 2 2>&1 | colout -t g++

addons:
  apt:
    packages:
      - cmake3
      - valgrind
    sources:
      - ppa:george-edison55/cmake-3.x
